root = "."
tmp_dir = "tmp"

[build] # The build configuration
  bin = "main"
  cmd = "go build -o {{.Output}} {{.Input}}"
  exclude = ["tmp/*", "client/*"]
  include = ["**/*.go"]
  ignore = ["tmp/*"]